### PR TITLE
Add promote with stanza list

### PR DESCRIPTION
**Pull request by mthambipillai**
This PR implements this enhancement: https://github.com/Kintyre/ksconf/issues/75

### CODE REVIEW

**Comment by lowell80** [comment]
Thanks for the contribution.  From a quick glance it all looks quite good!  I plan on taking a closer look and testing out the new code later today.

**Comment by mthambipillai** [comment]
@lowell80 did you have time to test/check the code in more details? Or do you think it can be merged?

**Comment by lowell80** [comment]
I may need a few more days.

**Comment by lowell80** [comment]
Thanks for your patience, it took longer to get some focused time on this than I thought it would.  This is really good work, thanks!

I have 2 design questions that I've been thinking through, and I'd welcome your feedback on.

### Mutually exclusive option vs modifier?
I notice that you have`--stanza` in the mutually exclusive group, adding a 3rd mode to the prior option of interactive vs batch.  So if the user provides `--stanza` they are essentially now in a non-interactive mode, and only what they have pre-selected will be promoted.  I guess I'd like to see these filter options apply to both batch and interactive modes.  In interactive mode, anything that doesn't automatically match the user's preselection they would be prompted to address.  Although, I suppose the same functionality could be achieved by calling promote first using stanza matching mode (batch operation as it's written now), and then call it again in interactive mode so anything that wasn't moved by the first command the user can sort through and promote as they see fit, just as they would now.  The just-run-ksconf-twice workaround feels a tad kludgy, but workable.

But the remaining concern is that (1) I'd like to add additional filter options some day besides just `--stanza`, and (2) I want to avoid CLI breakage in the future.

Here's what I'm thinking, tell me if this works:

1. Let's move `--stanza` into its own argparse group dedicated to "filtering".  This will make it a modifier action that can be applied to either interactive or batch modes.
1. Batch mode will be updated to call your new code, if `--stanza`(s) are given on the CLI.
1. If `--stanza` is used with `--interactive` (which is the default, mode).  The users will get some kind of "not-implemented-yet" response and told to use `--stanza` with `--batch` mode, until I get around to implementing that part.

I think this is the best answer long-term that doesn't break CLI compatibility.  As a user / developer, does this seem reasonable to you?

### Missing stanza behavior?
What are your thoughts behind aborting on non-matching stanzas?   I see where that could be desirable if you are *only* matching a single stanza, like if you know the stanzas you want to promote ahead of time and you want to know if you typed it wrong or something like that.  But I could see where this feature could be used in a situation where you have a long list of things to promote (if present) but you don't know ahead of time (for sure) which exact stanzas exist in SOURCE.  (Like a standing list of savedsearches that should always be pushed, if updated on a live system...idk)  I'd also like to quickly expand this to support various patterns rather than just string matches (see the `filter --match {regex,wildcard,string}` option), at which point finding rejected non-matches could be problematic.

Right now I'm leaning towards _not_ enforcing bad matches, at least by default.  But I'd love to hear your thoughts/rationale behind the current implementation.

Sorry for all the, processing-out-loud :-)

### Next steps

- I'm going to merge what you have into a feature branch and make some minor tweaks and explore the 2 topics I mentioned above.
- Give a shout if you have thoughts on either of the above 2 topics.
- I'll roll a beta release and ask you to test, if your time permits.
- Let me know how you'd like to be listed on the contributor list.

**Comment by mthambipillai** [comment]
Thanks for the review!

"Mutually exclusive option vs modifier?": sounds very good to me!

"Missing stanza behaviour": I see your point. The idea behind the current implementation is that if you already know the stanzas in advance, you expect to have no mismatch. In case there is a mismatch, because of a typo or because for some reason the stanza is actually not present, it indicates some potentially larger problem that you want to be aware of. In this case you want to abort the whole process, the rationale being that you want the promotion to be atomic: promote all or none. But this is only in my use case, indeed there can be use cases where you don't know in advance the stanzas to promote. I would add a flag boolean parameter `--fail-on-mismatch` with a default value set to `true` or `false` depending on what you think the most common use case will be.

**Comment by lowell80** [comment]
Thanks for the PR!  I didn't remember exactly how wonky the code was in places when we first started talking about this, so thanks for hanging in there!

Also I apologize that you're not showing up on the [contributors](https://github.com/Kintyre/ksconf/graphs/contributors) page, that must have done a merge step wrong somewhere along the way.

Regarding the `--fail-on-mismatch argument`, I like that idea, and I think it should be possible.  I think the default should be to allow mismatches to be silent, as I suspect that will be the more typical use case. I like the idea of an atomic operation, which certainly is the goal at a stanza level, and I like the idea of extending that to a group of related stanzas, when desirable.

Long term I think there should also be a `--report-on-mismatch` (as a mutually exclusive group with `--fail-on-mismatch`); which should be pretty easy to add too, but I'd want to think more about scenarios where that's valuable (so that's a nice-to-have/future thing).

I'm currently working on getting the `ksconf.filter.FilteredList` class to track filter "hits", to makei t possible to know which input rules have "matched."  I'm not sure I'll have time to get this all the way to the finish line soon, and I don't want it to be forgotten.  Would you mind either throwing out a new feature request issue, or a put together a PR?   If you make an issue, there's no need to go into full detail, a quick description and link to this PR is fine.  If you can run with a PR, I think you may be able to re-use some portions of your original logic.  I'll shout when I get the filter usage stats tracking in there.

**Comment by lowell80** [comment]
I think dbf1b82 now has the core filter-tracking features necessary to make ``--fail-on-mismatch` work.  The new unit tests should demonstrate finding unused filters:  [example]( https://github.com/Kintyre/ksconf/blob/master/tests/test_filter.py#L104)

**Pull request merged**
